"""ScaffoldDialog -- generates a plugin boilerplate .py file.

Produces a correctly structured standalone plugin (compatible with both
SVG_HOPE's PluginManager and the standalone StandalonePluginLoader) and
saves it to a user-chosen directory.
"""
from __future__ import annotations

import os

from PySide6.QtCore import Signal
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QFileDialog,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPlainTextEdit,
    QPushButton,
    QVBoxLayout,
)

_TEMPLATE = '''\
"""{description}

Generated by HOPE Plugin Tester scaffold wizard.
Compatible with SVG_HOPE PluginManager and standalone StandalonePluginLoader.
"""
from __future__ import annotations


class {class_name}:
    """Violation plugin: {plugin_id}."""

    def __init__(self, config: dict = None) -> None:
        self.config = config or {{}}
        # --- Read config values here ---
        # self.threshold = float(self.config.get("threshold", 10.0))

    def process_context(self, ctx) -> list:
        """Called once per tracked vehicle per frame.

        Parameters
        ----------
        ctx : ViolationContext (SVG_HOPE) or SimpleContext (standalone)
            Key helpers:
              ctx.track                       -- current Track
              ctx.frame                       -- BGR numpy ndarray
              ctx.camera                      -- Camera config object
              ctx.get_vehicle_lane()          -- Lane or None
              ctx.get_current_speed_mph()     -- float or None
              ctx.get_speed_limit_mph()       -- float or None

        Returns
        -------
        list[dict]
            Each dict is a violation event with keys:
                type, severity, track_id, details
            Optional keys: speed_mph, license_plate
        """
        violations = []

        # ── YOUR DETECTION LOGIC HERE ─────────────────────────────────
        #
        # Example: flag speeding
        # speed = ctx.get_current_speed_mph()
        # limit = ctx.get_speed_limit_mph()
        # if speed is not None and limit is not None and speed > limit:
        #     violations.append({{
        #         "type":      "{plugin_id}",
        #         "severity":  "high",
        #         "track_id":  ctx.track.track_id,
        #         "speed_mph": speed,
        #         "details":   f"Speed {{speed:.1f}} mph > limit {{limit}} mph",
        #     }})
        #
        # ─────────────────────────────────────────────────────────────

        return violations


# Optional: called by StandalonePluginLoader when loading the module-function form
def process_context(ctx) -> list:
    """Module-level entry point (standalone loader compatibility)."""
    return {class_name}().process_context(ctx)
'''


def _to_class_name(plugin_id: str) -> str:
    return "".join(p.capitalize() for p in plugin_id.replace("-", "_").split("_")) + "Plugin"


class ScaffoldDialog(QDialog):
    plugin_created = Signal(str)   # path of the newly created .py file

    def __init__(self, default_dir: str = "", parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle("New Plugin Scaffold")
        self.setMinimumWidth(520)

        form_box = QGroupBox("Plugin Details")
        form = QFormLayout(form_box)
        form.setVerticalSpacing(6)

        self._id_edit   = QLineEdit()
        self._id_edit.setPlaceholderText("my_violation_check")
        self._desc_edit = QLineEdit()
        self._desc_edit.setPlaceholderText("Detects vehicles doing X")
        self._dir_edit  = QLineEdit(default_dir)
        self._dir_edit.setPlaceholderText(r"D:\my_plugins\\")

        browse_btn = QPushButton("...")
        browse_btn.setFixedSize(28, 26)
        browse_btn.clicked.connect(self._pick_dir)

        dir_row = QHBoxLayout()
        dir_row.addWidget(self._dir_edit)
        dir_row.addWidget(browse_btn)

        form.addRow("Plugin ID:",     self._id_edit)
        form.addRow("Description:",   self._desc_edit)
        form.addRow("Save to dir:",   dir_row)

        # Preview
        prev_lbl = QLabel("Preview:")
        prev_lbl.setStyleSheet("color:rgba(255,255,255,0.6);font-size:10px;padding:4px 0 2px 0;")
        self._preview = QPlainTextEdit()
        self._preview.setReadOnly(True)
        self._preview.setFont(QFont("Consolas", 8))
        self._preview.setMaximumHeight(220)

        self._id_edit.textChanged.connect(self._refresh_preview)
        self._desc_edit.textChanged.connect(self._refresh_preview)
        self._refresh_preview()

        btns = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Save |
            QDialogButtonBox.StandardButton.Cancel
        )
        btns.accepted.connect(self._on_save)
        btns.rejected.connect(self.reject)

        layout = QVBoxLayout(self)
        layout.addWidget(form_box)
        layout.addWidget(prev_lbl)
        layout.addWidget(self._preview)
        layout.addWidget(btns)

    def _pick_dir(self) -> None:
        p = QFileDialog.getExistingDirectory(self, "Select directory", self._dir_edit.text())
        if p:
            self._dir_edit.setText(p)

    def _render(self) -> str:
        pid  = self._id_edit.text().strip()   or "my_plugin"
        desc = self._desc_edit.text().strip() or f"Violation plugin: {pid}"
        return _TEMPLATE.format(
            plugin_id=pid,
            class_name=_to_class_name(pid),
            description=desc,
        )

    def _refresh_preview(self) -> None:
        self._preview.setPlainText(self._render())

    def _on_save(self) -> None:
        pid = self._id_edit.text().strip()
        d   = self._dir_edit.text().strip()
        if not pid:
            QMessageBox.warning(self, "Missing ID", "Enter a plugin ID first.")
            return
        if not d or not os.path.isdir(d):
            QMessageBox.warning(self, "Invalid directory",
                                "Choose or create the destination directory first.")
            return
        path = os.path.join(d, pid + ".py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(self._render())
        self.plugin_created.emit(path)
        self.accept()
